# Generated by Django 4.1.7 on 2023-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.PositiveIntegerField(default=40000000),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
